### ISSUE TITLE
Updates, couple issues

### ISSUE THREAD

**Issue by wgodbout** [Tclack88/SortMusic#2]
First of all, this is brilliant! Thank you very much for this. A few updates I made when running this myself if you are interested.

With a library of sufficient size, the ABCD patterns can and do repeat in the various F## folders - this was causing files to get lost/overwritten. I solved this by adding the F## folder number to the new file name when moving it to the tempunsorted folder (ie: F00ABCD.mp3/m4a) - This is really the only major issue I found.

The title change and Sort functions had some issues (re: they wouldn't do anything w/ that file) if the song title had special characters in them. I added a regex check to just strip out any of the problematic ones I encountered, it may not be an exhaustive list though. I also further refined the Sort function to organize the files by Genre/Artist/Album - (ie: a file would end up at /tempunsorted/rock/the beatles/hey jude.mp3) - this was merely personal preference but was an easy extension from the existing code. 

Further, in the name change function, if the mp3 file is lacking tag information for the song title there were some issues, not much one can do about that I think since the info simply DNE but I have added functionality to output the errorlist in a txt file to more easily identify any such issues for manual fix once completed. This could be an issue with artist/album information missing the way I updated the code as well but I didn't seem to encounter that, so. The same could be done in the file move with the errorlist in that function but I have not done this.

See my updates below.

[sortmus.txt](https://github.com/Tclack88/SortMusic/files/5248781/sortmus.txt)

**Comment by wgodbout** [comment]
Note, here is another version of my updates with ONLY the fix for the issue of files being lost due to duplicate names - as this is the only *real* issue I encountered and the other fixes may cause different issues for any given users personal library 

[sortmus092020CollectMusOnly.txt](https://github.com/Tclack88/SortMusic/files/5248829/sortmus092020CollectMusOnly.txt)

**Comment by wgodbout** [comment]
After further testing I found that the ABCD sequence can be recycled within a given F## folder itself for different file types (IE: F00/ABCD.mp3 & F00/ABCD.mp4 both exist) - this was causing the same lost/overwritten issue mentioned above during mp4 -> mp3 conversion. I solved this by further editing the file name in the move to F##ABCDtyp.typ, ie F00ABCDmp4.mp4 - this way there is no issue when the mp4 -> mp3 conversion tries to save the newly converted mp3.

Also note I have only tested any of this in linux I do not know if any of my changes will work w/ windows

[sortmus092020CollectMusOnly.txt](https://github.com/Tclack88/SortMusic/files/5248878/sortmus092020CollectMusOnly.txt)

[sortmus.txt](https://github.com/Tclack88/SortMusic/files/5248876/sortmus.txt)

**Comment by Tclack88** [comment]
Hi I only just saw your suggestions. I never got a notification. I'm very happy for your contribution. Nice catch on the overwritten files, I didn't think to check for this. I will review these changes very soon. Sorry for the 1+ year gap

**Comment by Tclack88** [comment]
Implemented with most recent commit
